[package]
name = "crypto"
version = "6.6.3"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4"
log4rs = { version = "1.2", features = ["gzip"] }
clap = { version = "4.0", features = ["derive"] }
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.21", features = ["full"] }
hex = "0.4"
tower = "0.4.13"

cloud-util = { package = "cloud-util", git = "https://github.com/cita-cloud/cloud-common-rs.git" }
cita_cloud_proto = { package = "cita_cloud_proto", git = "https://github.com/cita-cloud/cloud-common-rs.git" }

libsm = "0.5"
efficient-sm2 = "0.1"
rayon = "1.5"
serde = "1.0"
serde_derive = "1.0"

backtrace = "0.3"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
