[package]
name = 'crypto'
version = '6.7.1-beta1'
license = 'Apache-2.0'
edition = '2021'
authors = ['Rivtower Technologies <contact@rivtower.com>']

[dependencies]
tonic = '0.9'
prost = '0.11'
hex = '0.4'
tower = '0.4'
libsm = '0.5'
efficient-sm2 = '0.2'
rayon = '1.7'
serde = '1.0'
serde_derive = '1.0'
tracing = '0.1'
cloud-util = '=0.7.1-beta1'
cita_cloud_proto = '=6.7.1-beta1'

[dependencies.clap]
version = '4.3'
features = ['derive']

[dependencies.tokio]
version = '1.29'
features = ['full']
[profile.release]
debug = 1
[profile.release.package."*"]
debug = 0
